---
title: "CVC Workshop Notes (Monday)"
author: "Randi Garcia"
date: "6/20/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


You can ask for all of the examples for a given function. 
```{r}
?boxplot
example(boxplot)
```

#Kidsfeet exercises

Question 1
```{r}
names(KidsFeet)

boxplot(KidsFeet$length ~ KidsFeet$sex)
boxplot(KidsFeet$width ~ KidsFeet$sex)

histogram(~KidsFeet$length|KidsFeet$sex)
histogram(KidsFeet$length)

t.test(KidsFeet$length~KidsFeet$sex, mu=0, alt="two.sided", conf=0.95, var.eq=F, paired=F)
```

Boys' feet are  little bit longer, but their mean foot length is not significantly higher than girls. 


Question 2: do boys and girls have differently shaped feet?
```{r}
table <- KidsFeet$biggerfoot
barplot(table)
summary(KidsFeet$biggerfoot)

xyplot(KidsFeet$length ~ KidsFeet$width, group=KidsFeet$sex)
```



```{r}
college_url <- "https://s3.amazonaws.com/ed-college-choice-public/Most+Recent+Cohorts+(All+Data+Elements).csv"
college_data <- read_csv(college_url)

library(readr)
anscombeurl <- "http://cvc.mosaic-web.org/Summer2016/Learn/ImportingData/Anscombe.csv"
anscombe <- read_csv(anscombeurl)



```

